# Generated by Django 5.1.2 on 2024-11-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report_maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.CharField(max_length=200)),
                ('activo', models.CharField(max_length=200)),
                ('code', models.IntegerField()),
                ('area_plant', models.CharField(blank=True, max_length=200, null=True)),
                ('area_office', models.CharField(blank=True, max_length=200, null=True)),
                ('area_building', models.CharField(blank=True, max_length=200, null=True)),
                ('mant_equipment', models.BooleanField(default=False)),
                ('mant_corrective', models.BooleanField(default=False)),
                ('mant_infrastructure', models.BooleanField(default=False)),
                ('mant_mejore', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('date_iniciate', models.DateTimeField()),
                ('mant_mecanic', models.BooleanField(default=False)),
                ('mant_electric', models.BooleanField(default=False)),
                ('mant_other', models.BooleanField(default=False)),
                ('worker_mant', models.CharField(max_length=200)),
                ('date_finish', models.DateTimeField()),
                ('recomendations', models.TextField()),
                ('time_respont', models.CharField(max_length=200)),
            ],
        ),
    ]
