# Generated by Django 5.1.2 on 2024-11-16 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker_plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_worker', models.CharField(max_length=200)),
                ('name_complete', models.CharField(max_length=400)),
                ('area_worker', models.CharField(max_length=100)),
                ('activo_worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activo_trabajador', to='activos.activos')),
            ],
        ),
    ]
