# Generated by Django 5.1.2 on 2024-11-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker_plant',
            name='name_complete',
        ),
        migrations.AddField(
            model_name='worker_plant',
            name='carge',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker_plant',
            name='last_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker_plant',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker_plant',
            name='code_worker',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
