# Generated by Django 5.1.2 on 2024-11-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_worker_plant_name_complete_worker_plant_carge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_plant',
            name='stade',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
