# Generated by Django 5.1.2 on 2024-12-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_worker_plant_stade'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_plant',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
