# Generated by Django 5.1.2 on 2024-11-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_activo', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('num_serie', models.CharField(max_length=10)),
                ('marc_activo', models.CharField(max_length=50)),
                ('plant_activo', models.CharField(max_length=50)),
                ('area_activo', models.CharField(max_length=100)),
                ('stade_activo', models.CharField(max_length=200)),
                ('value_activo', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True)),
                ('date_add', models.DateField()),
                ('life_activo', models.IntegerField(blank=True, null=True)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('guarantee_activo', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
