# Generated by Django 5.1.2 on 2024-12-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activos',
            name='code_activo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
