# Generated by Django 5.1.2 on 2024-12-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_activos_code_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activos',
            name='plant_activo',
        ),
        migrations.AlterField(
            model_name='activos',
            name='code_activo',
            field=models.BigIntegerField(),
        ),
    ]
