# Generated by Django 5.1.2 on 2025-01-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_remove_activos_plant_activo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activos',
            old_name='area_activo',
            new_name='areaActivo',
        ),
        migrations.RenameField(
            model_name='activos',
            old_name='category',
            new_name='categoriaActivo',
        ),
        migrations.RenameField(
            model_name='activos',
            old_name='code_activo',
            new_name='codigoActivo',
        ),
        migrations.RenameField(
            model_name='activos',
            old_name='name_activo',
            new_name='estadoActivo',
        ),
        migrations.RenameField(
            model_name='activos',
            old_name='date_add',
            new_name='fechaRegistro',
        ),
        migrations.RenameField(
            model_name='activos',
            old_name='marc_activo',
            new_name='marcaActivo',
        ),
        migrations.RenameField(
            model_name='activos',
            old_name='stade_activo',
            new_name='nombreActivo',
        ),
        migrations.RenameField(
            model_name='activos',
            old_name='num_serie',
            new_name='numeroSerie',
        ),
        migrations.RenameField(
            model_name='activos',
            old_name='last_maintenance',
            new_name='ultimoMantenimiento',
        ),
        migrations.RenameField(
            model_name='activos',
            old_name='value_activo',
            new_name='valorActivo',
        ),
        migrations.RemoveField(
            model_name='activos',
            name='guarantee_activo',
        ),
        migrations.RemoveField(
            model_name='activos',
            name='life_activo',
        ),
        migrations.AddField(
            model_name='activos',
            name='garantiaActivoTiempo',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
