# Generated by Django 5.1.2 on 2025-01-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_alter_activos_codigoactivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos',
            name='fechaRegistro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
