# Generated by Django 5.1.2 on 2025-01-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_alter_activos_fecharegistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos',
            name='garantiaActivoTiempo',
            field=models.CharField(max_length=200),
        ),
    ]
